% LAB 6

%%

% 6.1.1
% 1
%read the lexA file taken from the website
seq=fastaread('lexA.fasta');
position = length(seq(1).Sequence); % This assumes all sequences given are the same length
no_of_sequences = length(seq);
%Creating a matrix which calculates the probability of the sequences at
%each position with 
 Prob=zeros(4,no_of_sequences);
 for i=1:position
     pa=0;
     pg=0;
     pt=0;
     pc=0;
     for j=1:no_of_sequences
         
         seq_at_pos = upper(seq(j).Sequence(i));
         switch seq_at_pos
             case 'A'
                 pa=pa + 1;
             case 'G'
                 pg=pg + 1;
             case 'T'
                 pt= pt + 1;
             case 'C'
                 pc = pc +1;
         end
         
     Prob(1,i)=pa/no_of_sequences+ eps(0) ; %eps(0) added because later log value is to be calculated
     Prob(2,i)=pg/no_of_sequences+ eps(0);
     Prob(3,i)=pt/no_of_sequences+ eps(0) ;
     Prob(4,i)=pc/no_of_sequences+ eps(0);
     end
         
 end
 %Finding the H value using the formula given in the pdf
 H=zeros(1,length(Prob));
 for k=1:length(Prob)
     H(1,k)= - (Prob(1,k)*log(Prob(1,k)))- (Prob(2,k)*log(Prob(2,k)))-(Prob(3,k)*log(Prob(3,k)))-(Prob(4,k)*log(Prob(4,k)))
 end
 %Finding Rseq
 Rseq= 2 - H ;
 %%
 % 2
 % plot the graph of Rseq vs. position
 figure(1)
plot(1:position, Rseq)
title('Rseq vs. position plot')
ylim([0.9 2])
xlabel('Position')
ylabel('Bits')

%bi table
bi=zeros(4,20);
for i=1:4
    for l=1:20
       bi(i,l)= Prob(i,l).*Rseq(l)
    end
end
%%
% 6.2.1
% Generating the sequence logo
[W, handle] = seqlogo(seq);
% Sequence logo generated online
figure(2)
imshow('pic.png')
title({'Rseq vs Position Plot', 'Generated by Web Logo'})
% As we can see from all three plots, the general trend is the same.
% Where there are large features at positions 3,4,5, 16, 17, 18 and so on
